### PR TITLE
 Allow student to open a quiz if status is inprogress

### PR DESCRIPTION
**Pull request by ankitjavalkar**
- The system will now allow student to open a quiz if status is in-progress redirect to completion page if attempts are exceeded.
- Fix the condition to evaluate the number of attempts

### CODE REVIEW

**Comment by ankitjavalkar** [comment]
Please review. Will fix the PEP8 issues at the very end.

**Comment by prathamesh920** [comment]
We can merge this after the tests and PEP8 issues are fixed.

**Comment by ankitjavalkar** [comment]
@prathamesh920 Please note that the test case coverage cannot be fixed [see screenshot] even after adding more test cases and modifying existing ones. In fact the coverage even deteriorates,

I have raised an issue to add test cases for the complete view and will send a separate PR to improve the test case  coverage

codecov1

**Comment by prathamesh920** [comment]
LGTM

**Pull request merged**
