### PR TITLE
Add syntax highlight for code answers in answerpaper

### PR DESCRIPTION
**Pull request by ankitjavalkar**
Fixed conflicts in #523 and submitted fresh PR

@adityacp @CruiseDevice Kindly review.

### CODE REVIEW

**Comment by CruiseDevice** [comment]
LGTM

**Comment by adityacp** [comment]
LGTM

**Comment by maheshgudi** [comment]
@ankitjavalkar @adityacp While at the time I thought this was a good idea, in retrospect though, I think this is somewhat expensive to be done from the backend.  Maybe doing it using codemirror would be far less intensive. Just a suggestion though, please consider it if you can.

**Comment by adityacp** [comment]
I feel it is ok to have it on the server side for now. We can check it on the production, if it makes lot of difference in the response time then we can add this to the client side.

**Pull request merged**
