### PR TITLE
Update Login UI 

### PR DESCRIPTION
**Pull request by NeoHimu**
basic cleanup which includes removing history and ad informations from the login page

### CODE REVIEW

**Comment by prathamesh920** [comment]
Please refer the issue number here.

**Comment by prathamesh920** [comment]
Also, the login page is the landing page for all the users and the write up is missing.
I think we should have a small write up for Yaksh.

**Comment by ankitjavalkar** [comment]
> Also, the login page is the landing page for all the users and the write up is missing.
I think we should have a small write up for Yaksh.

@prathamesh920 Maybe, but this was done after feedback from @prabhuramachandran 
In order to keep the application generic, the page can be kept blank. Otherwise, @NeoHimu please create an issue for this and kindly check what content needs to be added and add it to this PR

**Comment by ankitjavalkar** [comment]
@NeoHimu the migration file should not have been committed in the first place. Kindly undo the latest commit, remove the migration file and use ```commit --amend``` to ensure that there is only one commit.

**Comment by ankitjavalkar** [comment]
Closing the PR as the migration files were not completely erased from commits as advised.

**Pull request closed without merging**
