### PR TITLE
Bump django version to 3.0.3

### PR DESCRIPTION
**Pull request by adityacp**

### CODE REVIEW

**Comment by adityacp** [comment]
Did you update the Django 1.11 to 3.0.3? Paginator `get_page` function is new in Django 3. It is not available in Django 1.11.

**Comment by CruiseDevice** [comment]
Updating python version to 3.6 and then installing the Django 3.0.3 fixes this issue.

**Comment by CruiseDevice** [comment]
LGTM

**Comment by ankitjavalkar** [comment]
* All references to the ```six``` module need to be removed.
* We have used encode/decode multiple times to be able to support both Py2 & Py3, that needs to go as well.

**Comment by adityacp** [comment]
I have removed the `six` module. encode/decode was used specifically for python 3. Removing encode/decode causes TypeError. So  I feel it is okay to keep it as it is.

**Pull request merged**
